# Generated by Django 5.2.9 on 2025-12-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'nome_social',
                    models.CharField(
                        max_length=150, verbose_name='Nome Social'
                    ),
                ),
                (
                    'nome_registro',
                    models.CharField(
                        help_text='Para fins de documentos oficiais',
                        max_length=150,
                        verbose_name='Nome de Registro',
                    ),
                ),
                (
                    'profissao',
                    models.CharField(
                        choices=[
                            ('MED', 'Médico(a)'),
                            ('PSI', 'Psicólogo(a)'),
                            ('ENF', 'Enfermeiro(a)'),
                        ],
                        max_length=3,
                        verbose_name='Profissão',
                    ),
                ),
                (
                    'registro_profissional',
                    models.CharField(
                        max_length=50, verbose_name='Registro (ex: CRM/CRP)'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name='E-mail de Contato',
                    ),
                ),
                (
                    'telefone',
                    models.CharField(
                        max_length=20, verbose_name='Telefone/WhatsApp'
                    ),
                ),
                (
                    'logradouro',
                    models.CharField(max_length=255, verbose_name='Endereço'),
                ),
                (
                    'cidade',
                    models.CharField(max_length=100, verbose_name='Cidade'),
                ),
                (
                    'estado',
                    models.CharField(max_length=2, verbose_name='Estado'),
                ),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
