name: CI - API Médica Lacrei

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: api_medica_db
          POSTGRES_USER: user_lacrei
          POSTGRES_PASSWORD: lacre_pass  # Alinhado com o que o seu Django está pedindo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalando versões específicas que suportam Python 3.12
          pip install "flake8>=7.0.0"
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov blue bleach python-dotenv

      - name: Lint with Flake8
        run: |
          # Para o build se houver erros de sintaxe Python ou símbolos indefinidos
          # exit-zero trata os erros como avisos (nós queremos que ele PARE, então não usaremos)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # O padrão da Lacrei: verifica erros de estilo (PEP8)
          flake8 . --count --max-complexity=10 --max-line-length=150 --statistics

      - name: Run Tests and Coverage
        env:
          # Estas variáveis forçam o Django a ignorar arquivos locais durante o teste no GitHub
          DB_NAME: api_medica_db
          DB_USER: user_lacrei
          DB_PASSWORD: lacre_pass      # Senha igual ao serviço acima
          DB_HOST: localhost
          DB_PORT: 5432
          DATABASE_URL: postgres://user_lacrei:lacre_pass@localhost:5432/api_medica_db
          SECRET_KEY: test_secret_key
          DEBUG: "True"
        run: |
          pytest --cov=users --cov-report=xml